### ISSUE TITLE
Local hosting environment

### ISSUE THREAD

**Issue by lmkw** [data2health/competitions-project#9]

**Comment by firaswehbe** [comment]
Update: Chartstring info sent to Dong Fu from FSM IT for NU AWS instance

**Comment by lmkw** [comment]
Update:   Feinberg IT got access to the AWS account that is setup for the project.   However, before VM deployment, the Cloud Operations and Networking teams of Northwestern IT needs to set up the proper networking (VPN, etc.) to enable the direct network traffic back to campus.   They are expecting a two week’s lead time right now before this setup can be completed due to competing priorities and projects.   Upon networking setup completion, we anticipate another day or two for VM deployment, setup and validation.
